services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=personal_notes_db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

volumes:
  postgres_data:
